### ISSUE TITLE
Version 1 checklist

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/sdxpy#181]
- [x] Introduction
- [x] Objects and Classes
- [x] Finding Duplicate Files
- [x] Matching Patterns
- [x] Parsing Text
- [x] Running Tests
- [x] An Interpreter
- [x] Functions and Closures
- [x] Protocols
- [x] A File Archiver
- [x] An HTML Validator
- [x] A Template Expander
- [x] A Code Linter
- [x] Page Layout
- [x] Performance Profiling
- [x] Object Persistence
- [x] Binary Data
- [x] A Database
- [x] A Build Manager
- [x] A Package Manager
- [x] Transferring Files
- [x] Serving Web Pages
- [x] A File Viewer
- [x] Undo and Redo
- [x] A Virtual Machine
- [x] A Debugger
- [x] Conclusion
- [x] Bibliography
- [x] Bonus Material
- [x] Syllabus
- [x] License
- [x] Code of Conduct
- [x] Contributing
- [x] Glossary
- [x] Credits
- [ ] Index
