### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/sdxpy#240]
## Manuscript

- [x] The manuscript is complete with no missing material and all files are the final versions
- [x] Chapter titles and author names exactly match the supplied table of contents
- [x] A reference style has been used consistently throughout all chapters and all cited references are included in a bibliography/reference list
- [x] An abstract has been provided for each chapter
- [x] Each author has provided an ORCID iD (www.orcid.org)

## Content

The following front matter and end matter is supplied where required:

- [x] Title page (mandatory)
- [x] Dedication
- [x] Table of contents (mandatory)
- [x] List of figures/tables/images
- [x] Author/editor biographies
- [x] Acknowledgements
- [x] Appendices

## Figures and Tables

- [x] All figures have been supplied as separate files (tables can remain within the chapter files)
- [x] Halftone (photo) figures are supplied at a minimum width of 1500 pixels
- [x] Line drawings (charts/diagrams) are supplied as editable files in the software in which they were created (i.e. excel), or with a minimum width of 6000 pixels
- [x] Each figure is clearly numbered and labelled consecutively
- [x] Callouts are provided indicating where figures should be inserted
- [x] Where captions are required, captions are supplied within the chapter files
- [x] Alt Text has been submitted for each figure.

## Permissions

- [x] All necessary permissions to reproduce copyright material have been obtained and correspondence with the copyright holders is enclosed
- [x] The Permissions Declaration Form has been signed and returned

Please note that manuscripts cannot enter the production process until all permissions have been received

## Additional Information

- [x] I have informed my Editorial Assistant that I would like to compile the index myself
- [x] I have provided a Notes for Copyeditor/Production document if I have any special manuscript requirements
- [x] I have attached the MIR form.
